apiVersion: apps/v1
kind: Deployment
metadata:
  name:  local-registry
  namespace: registry
  labels:
    app:  local-registry
spec:
  selector:
    matchLabels:
      app: local-registry
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  local-registry
    spec:
      containers:
      - name:  local-registry
        image: registry:2
        ports:
          - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: registry-svc
  namespace: registry
spec:
  selector:
    app: local-registry
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
---      
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: registry-ingress
  namespace: registry
spec:
  ingressClassName: traefik
  rules:
  - host: reg.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: registry-svc
            port:
              number: 5000
---
