apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: fwdauth-check
  namespace: dev
spec:
  forwardAuth:
    address: http://fwd-auth-svc.dev:8080/check
    authResponseHeaders:
      - x-user-id
