apiVersion: apps/v1
kind: Deployment
metadata:
  name:  fwd-auth-middleware
  namespace: dev
  labels:
    app:  fwd-auth-middleware
spec:
  selector:
    matchLabels:
      app: fwd-auth-middleware
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  fwd-auth-middleware
    spec:
      containers:
      - name:  fwd-auth-middleware
        image: reg.local/fwd-auth-middleware:latest
        envFrom:
          - secretRef:
              name: fwd-auth-secret
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: fwd-auth-svc
  namespace: dev
spec:
  selector:
    app: fwd-auth-middleware
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
